name: automatic weekly deadlink checker

on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run weekly-link-check